const airlines = [
	['3K', 'Jetstar Asia Airways'],
	// ['4U', 'Germanwings'],
	['6E', 'IndiGo Air'],
	['8M', 'Myanmar Airways Intl'],
	// ['8Z', 'Wizz Air Bulgaria'],
	['9F', 'Eurostar'],
	['9W', 'Jet Airways India'],
	['A3', 'Aegean Air'],
	['A5', 'HOP'],
	['AA', 'American Airlines'],
	// ['AB', 'Air Berlin'],
	['AC', 'Air Canada'],
	['AF', 'Air France'],
	['AI', 'Air India'],
	['AR', 'Aerolineas Argentinas'],
	['AS', 'Alaska Airlines'],
	['AT', 'Royal Air Maroc'],
	['AY', 'Finnair'],
	['AZ', 'Alitalia'],
	['BA', 'British Airways'],
	['BD', 'Bmi British Midland'],
	['BE', 'Flybe'],
	['BF', 'French Bee'],
	['BG', 'Biman Bangladesh'],
	['BI', 'Royal Brunei Air'],
	['BL', 'Jetstar Pacific'],
	['BM', 'British Midland'],
	['BR', 'Eva Airways Corporation'],
	['BY', 'TUI'],
	['CA', 'Air China'],
	['CG', 'PNG Air'],
	['CI', 'China Airlines'],
	['CO', 'Continental Airlines'],
	['CX', 'Cathay Pacific Airways'],
	['CZ', 'China Southern Airlines'],
	['D8', 'Norwegian'],
	['DD', 'Nok Air'],
	['DE', 'Condor'],
	['DF', 'Condor Berlin'],
	['DL', 'Delta Air Lines'],
	// ['DN', 'Senegal Airlines'],
	// ['DR', 'Air Link Pty Ltd'],
	['DX', 'Danish Air'],
	['DY', 'Norwegian Air Shuttle'],
	['EI', 'Aer Lingus P.L.C.'],
	['EK', 'Emirates Airlines'],
	['ET', 'Ethiopian Air Lines'],
	['EY', 'Etihad Airways'],
	['EW', 'Eurowings'],
	['F9', 'Frontier Airlines'],
	['FB', 'Bulgaria Air'],
	['FI', 'Icelandair'],
	['FJ', 'Fiji Airways'],
	['FM', 'Shanghai Airlines'],
	// ['FQ', 'Brindabella Airlines'],
	['FR', 'Ryanair (Ireland)'],
	['FT', 'FlyEgypt'],
	['FZ', 'Fly Dubai'],
	['GA', 'Garuda Indonesian'],
	// ['GE', 'Transasia Airways'],
	['GF', 'Gulf Air Company'],
	['GK', 'Jetstar Japan'],
	['H1', 'Hahn Air Systems'],
	['HA', 'Hawaiian Airlines'],
	// ['HQ', 'Thomas Cook BE'],
	['HV', 'Transavia'],
	['HX', 'Hong Kong Airlines'],
	['IB', 'Iberia'],
	// ['IC', 'Indian Airlines'],
	['IE', 'Solomon Airlines'],
	// ['IT', 'Kingfisher Airlines'],
	['JG', 'JetGo Australia'],
	['JL', 'Japan Airlines International'],
	['JQ', 'Jetstar Airways'],
	['KA', 'Cathay Dragon Airlines'],
	['KE', 'Korean Air'],
	['KL', 'Klm Royal Dutch Airlines'],
	['KM', 'Air Malta'],
	['KQ', 'Kenya Airways'],
	['KU', 'Kuwait Airways'],
	['LA', 'LATAM Airlines'],
	['LG', 'Luxair'],
	['LH', 'Lufthansa'],
	['LM', 'Loganair'],
	['LN', 'Libyan Airlines'],
	['LO', 'LOT Polish'],
	['LS', 'Jet2.Com'],
	['LX', 'Swiss'],
	['MD', 'Air Madagascar'],
	['ME', 'Middle East Airlines'],
	['MF', 'Xiamen Airlines'],
	['MH', 'Malaysia Airline'],
	['MI', 'Silkair'],
	['MS', 'Egyptair'],
	['MT', 'Thomas Cook Air'],
	['MU', 'China Eastern Airlines'],
	['NF', 'Air Vanuatu Limited'],
	['NH', 'All Nippon Airways'],
	['NK', 'Spirit Airlines'],
	['NP', 'NILE AIR'],
	// ['NW', 'Northwest Airlines Inc'],
	['NZ', 'Air New Zealand'],
	['NY', 'Air Iceland'],
	// ['O7', 'Ozjet Airlines'],
	['OA', 'Olympic Air'],
	['OD', 'MALINDO AIRWAYS'],
	['OI', 'Hinterland Aviation'],
	['OK', 'Czech Airlines'],
	['OS', 'Austrian Airlines'],
	['OT', 'Aeropelican'],
	['OU', 'Croatia Airlines'],
	['OZ', 'Asiana Airlines'],
	['PG', 'Bangkok Airways'],
	['PR', 'Philippine Airlines'],
	['PX', 'Air Niugini'],
	['Q6', 'Skytrans Airlines'],
	['QF', 'Qantas Airways'],
	// ['QO', 'Origin Pacific Airways'],
	['QQ', 'Alliance Airlines'],
	['QR', 'Qatar Airways'],
	['RJ', 'Royal Jordanian'],
	['RO', 'Tarom-Romanian'],
	['S2', 'Jet Lite'],
	['S8', 'Sounds Air'],
	['SA', 'South African Airways'],
	['SB', 'Air Calin'],
	['SG', 'Spice Jet'],
	['SK', 'Sas Scandinavian Airlines'],
	['SN', 'Brussels Airlines'],
	['SQ', 'Singapore Airlines'],
	['SU', 'Aeroflot Russian Airlines'],
	['SV', 'Saudi Arabian Airlines'],
	['T3', 'Easter Airways'],
	['TG', 'Thai Airways'],
	['TK', 'Turkish Airlines'],
	['TL', 'Air North Regional'],
	['TN', 'Air Tahiti Nui'],
	['TP', 'Air Portugal'],
	['TR', 'Scoot Pty Ltd'],
	['U2', 'Easy Jet'],
	['UA', 'United Airlines Inc'],
	['UK', 'VISTARA'],
	['UL', 'Srilankan Airlines'],
	['UO', 'Hong Kong Express Airways'],
	// ['US', 'Us Airways'],
	['UX', 'Air Europa'],
	['VA', 'Virgin Australia'],
	// ['VC', 'Strategic Airlines'],
	// ['VF', 'Valuair Ltd'],
	['VG', 'VLM Airlines'],
	['VN', 'Vietnam Airlines'],
	['VS', 'Virgin Atlantic Airways Ltd.'],
	['VX', 'Virgin America'],
	['VY', 'Vueling Airlines'],
	['W6', 'Wizz Air Hungary'],
	['WF', 'Wideroes Flyvese'],
	['WN', 'Southwest Airlines'],
	['WW', 'Wow Air'],
	['WX', 'CityJet'],
	['WY', 'Oman Aviation'],
	['XR', 'Skywest Airlines'],
	['XY', 'flynas'],
	['ZL', 'Regional Express']
];

export default airlines;